services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: "1.24.0" 
    ports:
      - "3000:3000"
    environment:
      - ENV=production
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_BOT_URL=${DISCORD_BOT_URL}
    command: ["/usr/local/bin/run-app"]
